### ISSUE TITLE
Пункт "Параметр функции не должен возвращать значение"

### ISSUE THREAD

**Issue by JohnyDeath** [skyksandr/1c-styleguide#2]
Пункт "Параметр функции не должен возвращать значение" противоречит ИТС, где примеры "Хорошо" и "Плохо" прямо противоположны вашим

**Comment by skyksandr** [comment]
А можно ссылку на ИТС?
Данный пункт основан на книгах С. Макконелла "Совершенный код" и книге Р. Мартина "Чистый код".

**Comment by JohnyDeath** [comment]
Примерно так: http://stimul.kiev.ua/materialy.htm?a=rabota_s_parametrom_laquootkazraquo_v_obrabotchikakh_sobytiy
На ИТС здесь: http://its.1c.ru/db/v8std#content:2149184335:hdoc

**Comment by nixel2007** [comment]
Ненене. Не путайте работу с параметром отказ и с вощвращаемым функцией значением. 

Если я правильно понимаю саму суть проверки, то имеется ввиду, что не надо использовать входные параметры функций как дополнительный вывод. Весь вывод должен быть в возвращаемом значении. В структуре, если нужно возвращать несколько значений.

**Comment by JohnyDeath** [comment]
Одна из самых популярных ф-ий БСП становится невалидной

**Comment by nixel2007** [comment]
Я понял, про что @JohnyDeath 
В примере кода идёт присваивание переменной "Отказ", которая является во многих обработчиках. Такое делать нельзя, так как можно потерять уже  значение ИСТИНА. Надо просто сменить имя переменной

**Comment by JohnyDeath** [comment]
Да, здесь в примере явно что-то из обработчика проведения.

**Comment by skyksandr** [comment]
Дополнил описание пункта и заменил пример:

Параметр функции не должен возвращать значение. Иными словами не используйте входные параметры функций как дополнительный вывод. Весь вывод должен быть в возвращаемом значении. Если нужно возвращать несколько значений следует использовать такие типы как Структура, Массив и т.д.

``` bsl
// Плохо:
URLСервиса = "";
ИмяПользователя = "";
ПарольПользователя = "";

ЗаполнитьПараметрыПодключения(URLСервиса, ИмяПользователя, Пароль);

// Хорошо:
ПараметрыПодключения = ПолучитьПараметрыПодключения();
// Возвращаемое значение - структура:
//     URLСервиса         - Строка
//     ИмяПользователя    - Строка
//     ПарольПользователя - Строка
```
