### ISSUE TITLE
Выравнивание по пробелу

### ISSUE THREAD

**Issue by JohnyDeath** [skyksandr/1c-styleguide#3]
> Выравнивание однотипных операторов. При следовании друг за другом нескольких однотипных операторов допускается их выравнивание. Выравнивание следует выполнять с помощью пробелов

Почему выравнивание по пробелам? Это ж вечный холивар, а у 1С пока принят ТАБ.

**Comment by skyksandr** [comment]
Если использовать выравнивание по табу - при изменении отступа по табу в настройках конфигуратора весь текст разъезжается, если использовать по пробелу - нет.

``` bsl
    ДругаяПеременная = 2;
    Переменная1      = 1;
^[таб]         ^[пробелы]     
```

**Comment by JohnyDeath** [comment]
А зачем его менять в настройках?
Ни разу не видел, чтобы одинэсники изменяли этот пункт в настройках

**Comment by skyksandr** [comment]
Например, можно поменять на 2, чтобы компактнее все выглядело.
В целом большинство одинэсников не меняет никаких настроек.

Нашел на ИТС. Они также рекомендуют выравнивать относительно первой строки пробелами, чтобы не разъехалось. 
![2016-11-13 13 53 50](https://cloud.githubusercontent.com/assets/5262979/20245067/abcdd706-a9a8-11e6-9c02-190768aaafe0.png)

**Comment by JohnyDeath** [comment]
Тут, насколько я понял, речь идет о многострочных условиях.

В общем, как обычно начинается TAB VS Spaces )
https://www.youtube.com/watch?v=SsoOG6ZeyUI

**Comment by dmpas** [comment]
@JohnyDeath выравнивание по пробелам - всё верно. Выравнивание не отступ, отступ - табами.
Я надеюсь, тут не "TAB VS Spaces", а соответствие СРК обсуждается.

**Comment by skyksandr** [comment]
@dmpas, все верно. Отступ - табы, выравнивание - пробелы.

**Comment by skyksandr** [comment]
Закрываю по причине отсутствия активности.
