### ISSUE TITLE
Пример в сложных условиях.

### ISSUE THREAD

**Issue by afanasko** [skyksandr/1c-styleguide#4]
В примере "хорошо" для сложных условий приведен код функции выполняющей проверку условия:
```bsl
Функция ОткрыватьОбъектПриИдентификаторе(ИдентификаторОбъекта)

    ДопустимыеИдентификаторы = Новый Структура("
    |АнализСубконто,
    |АнализСчета,
    |ОборотноСальдоваяВедомость,
    |ОборотноСальдоваяВедомостьПоСчету,
    |ОборотыМеждуСубконто,
    |ОборотыСчета,
    |СводныеПроводки,
    |ГлавнаяКнига,
    |ШахматнаяВедомость");

    Возврат ДопустимыеИдентификаторы.Свойство(ИдентификаторОбъекта);

КонецФункции
```
На мой взгляд пример скорее плох, чем хорош. Вместо ленивой цепочки условий (в самом лучшем случае сравнение будет одно), тратится время на создание структуры и поиск ключа. 

Предлагаю переписать пример так:
```bsl
Функция ОткрыватьОбъектПриИдентификаторе(ИдентификаторОбъекта)
	
    Возврат ИдентификаторОбъекта = "АнализСубконто"
        ИЛИ ИдентификаторОбъекта = "АнализСчета"
        ИЛИ ИдентификаторОбъекта = "ОборотноСальдоваяВедомость"
        ИЛИ ИдентификаторОбъекта = "ОборотноСальдоваяВедомостьПоСчету"
        ИЛИ ИдентификаторОбъекта = "ОборотыМеждуСубконто"
        ИЛИ ИдентификаторОбъекта = "ОборотыСчета"
        ИЛИ ИдентификаторОбъекта = "СводныеПроводки" 
        ИЛИ ИдентификаторОбъекта = "ГлавнаяКнига"
        ИЛИ ИдентификаторОбъекта = "ШахматнаяВедомость"

КонецФункции
```

**Comment by karnilaev** [comment]
На мой взгляд в данном конкретном примере оба варианта хороши.
Главное в такой маленькой процедуре - читаемость, а не производительность. 
По производительности сомневаюсь что первый вариант окажет существенное влияние на общую производительность системы по сравнению со вторым.

**Comment by afanasko** [comment]
На общую производительность конечно не окажет. Тут важно знать контекст выполнения этой или похожей функции.
Но с точки зрения оверинжиниринга первый вариант хуже второго. Считаю, что если решились писать о том, как нужно делать "хорошо", то и примеры должны быть максимально хорошими. Какой-нибудь неокрепший ум прочитает этот гайдлайн и будет пихать структуры везде, где можно обойтись элементарными операциями. 
Оккам вам такого не простит :)

**Comment by skyksandr** [comment]
Согласен. Внес изменения.
По большей части по причине того, что данный пункт про то, что нужно выносить сложные условия в отдельные методы, чтобы сделать код более читаемым.
