### ISSUE TITLE
Использование возвращаемых параметров

### ISSUE THREAD

**Issue by afanasko** [skyksandr/1c-styleguide#5]
> Параметр функции не должен возвращать значение. Иными словами не используйте входные параметры функций как дополнительный вывод. Весь вывод должен быть в возвращаемом значении. Если нужно возвращать несколько значений следует использовать такие типы как Структура, Массив и т.д.

Довольно спорный пункт, особенно в свете того, что существуют встроенные функции с таким поведением. Например, метод Свойство() у объекта Структура.

Часто бывает, что  нужно передать в процедуру какой-то объект, обработать его и вернуть назад. В таких случаях использовать изменяемые параметры оптимальнее, чем возвращать результат отдельно.

**Comment by artbear** [comment]
+1

**Comment by karnilaev** [comment]
Код в первую очередь должен быть читаемым, а уже потом оптимальным. Если ты видишь код в первый раз то бывает нужно потратить больше времени на понимание кода, если у него есть параметры, в которых возвращается значение, чем если значение возвращается функцией.

**Comment by skyksandr** [comment]
Обсуждали в #2 
Данный пункт описан в двух книгах: "Чистый код" и "Совершенный код".
Основная мысль в том, что код читают куда большее количество раз, чем пишут. 
Использование параметров для изменения переданного значения - это не явное действие, что увеличит время, затраченное на понимание того, как это работает.

**Comment by afanasko** [comment]
Извиняюсь, что не читаю закрытые issue.

**Comment by nixel2007** [comment]
За функцию "Свойство" у структуры 1с ждёт отдельный котёл...
